### ISSUE TITLE
The diagnostic class doesn't work with cell-based fields.

### ISSUE THREAD

**Issue by Swanekamp** [NRL-Plasma-Physics-Division/turbopy#111]

**Comment by Swanekamp** [comment]
Error message:
Traceback (most recent call last):
  File "C:\Users\swane\Documents\Codes\turbopy-fct\fct.py", line 265, in <module>
    sim.run()
  File "c:\users\swane\documents\codes\turbopy\turbopy\core.py", line 140, in run
    self.fundamental_cycle()
  File "c:\users\swane\documents\codes\turbopy\turbopy\core.py", line 153, in fundamental_cycle
    d.diagnose()
  File "c:\users\swane\documents\codes\turbopy\turbopy\diagnostics.py", line 231, in do_diagnostic
    self.output_function(self.field)
  File "c:\users\swane\documents\codes\turbopy\turbopy\diagnostics.py", line 295, in csv_diagnose
    self.csv.append(data)
  File "c:\users\swane\documents\codes\turbopy\turbopy\diagnostics.py", line 52, in append
    self.buffer[self.buffer_index, :] = data
ValueError: could not broadcast input array from shape (63) into shape (64)

**Comment by GarethTMorgan** [comment]
The size of the array is changed in the process of centering data points.

**Comment by GarethTMorgan** [comment]
Error is given because FieldDiagnostic was not using the amended array size. PR #112 addresses this issue by having the size be pulled from the amended field size array.
